CREATE TABLE GCG_4121_VendorAddl(
 Vendor VARCHAR(20),
 Bank_Account_Type VARCHAR(1),
 Bank_Routing_Num VARCHAR(20),
 Bank_Account_Num VARCHAR(30),
 Vendor_Curr VARCHAR(3),
 NAME_VENDOR_PAY VARCHAR(30),
 ADDRESS1_PAY VARCHAR(30),
 ADDRESS2_PAY VARCHAR(30),
 CITY_PAY VARCHAR(20),
 STATE_PAY VARCHAR(2),
 CODE_ZIP_PAY VARCHAR(13),
 COUNTRY_PAY VARCHAR(12),
 ATTENTION_PAY VARCHAR(30));